name: algoritimos_api_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - fastapi==0.109.0
      - uvicorn==0.25.0
      - loguru==0.7.2
      - python-jose==3.3.0
      - passlib[bcrypt]==1.7.4
      - prometheus-fastapi-instrumentator==7.1.0
      - mkdocs==1.5.3
      - flake8==6.1.0
      - pytest==8.2.2
      - pytest-asyncio==1.0.0
      - coverage==7.3.2
